version: '3.8'

services:
#  backend:
#    container_name: "backend"
#    restart: always
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    volumes:
#      - ./backend/:/backend/
#    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
#    env_file:
#      - ./backend/.env
#    ports:
#      - 8000:8000


  db:
    container_name: "db"
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postresql/data/
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"


#  db_test:
#    container_name: "db_test"
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres_test
#      - POSTGRES_PASSWORD=postgres_test
#      - POSTGRES_DB=postgres_test
#    ports:
#      - "5434:5432"
#    networks:
#      - custom

volumes:
  postgres_data:

#networks:
#  custom:
#    driver: bridge
